### PR TITLE
create index.html

### PR DESCRIPTION
**Pull request by HolyRaveOS**

### CODE REVIEW

**Review by HolyRaveOS — COMMENTED** [review]
[My page](https://holyraveos.github.io/mateRepo/)

**Comment by HolyRaveOS** [comment]
My page https://holyraveos.github.io/mateRepo/

**Comment by DenNice-cloud** [comment]
It's fine, but you should have posted a comment like "**\[** My Page **\]\(** Link **\)**". :-)

**Comment by BudnikOleksii** [comment]
You should create a PR to [mate-academy:master](https://github.com/mate-academy/layout_hello-world/tree/master) branch instead of your main brainch

**Pull request merged**
